Remove buggy check
It’s causing false alert when there’s force push:
```
Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.
```

See https://github.com/jitterbit/get-changed-files/commit/54f37035de4da94142f10f4ad576c04869f4150e